# Generated by Django 3.1.7 on 2021-06-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
