# Generated by Django 3.1.7 on 2021-06-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0002_auto_20210616_1343'),
        ('login', '0003_auto_20210616_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAdmin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userprofile.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('userprofile.user',),
        ),
    ]
